### ISSUE TITLE
データベースアクセス

### ISSUE THREAD

**Issue by takashno** [temp-go-dev/consider#10]
# データベースアクセス

## 目的・概要・ゴール
- 目的
  - GoLangでのデータベースアクセスの方法を調査
  - GoLangで利用できるORMapperを調査。

- 概要
ORMapperを調査、使用する際にデファクトとできそうなレベルのものを選定する。
そもそも使う必要があるのか？くらいからの可能性がある。
 
  - 要件等ポイント
      - 実装のしやすさ
         - SQLを直接記載できるか（そうじゃない方がよければそこも見極めたい）
         - ロギング（開発時のSQL出力、商用エラー時に何がでるのか。わざとSQLエラーにしてやってみるとか）
         - ConnectTimeoutの設定
         - ReadTimeoutの設定（soTimeout）
         - TEXTの扱い

- ゴール
決定

## 執筆ページ
https://github.com/temp-go-dev/consider/blob/feature/10_database_access/decisions/0004-database-access.md

**Comment by awaduharatk** [comment]
GORMのトランザクションは開始、ロールバック、コミットを書く必要があり、冗長になってしまう。
トランザクションマネージャ(Springの@Transactionalみたいな)のようなものを用意したい。
(ginのhttps://qiita.com/tobita0000/items/d2309cc3f0dd32006eadなどを利用するのがよさそう）

**Comment by takashno** [comment]
極力トランザクション制御は、ビジネスロジックに入れないようにしたいです。
制約事項として、REST-APIは１リクエスト１トランザクションでSpringのようにトランザクション境界がServiceで切れないかもしれないというところが出てきそうかもしれませんね。

あと、実運用においてデータベースはMaster/Replica構成である場合が多いです。
その場合に読み書きを別のコネクション（GORMの接続）を保持しなければならないかもしれません。
単純にServiceから参照するdbを別のものにすればいいですよ。とかであればあまり問題ないのですが実際にどういう手段がとれるのかも確認しておきたいです。

AWSのAuroraに対するMariaDBConnectorのような特殊なものがあるのか・ないのかも深堀して調査する前にあるのか？くらいまでは知っておきたいですね。
なんかボリューム増えてしまってすみません・・・

**Comment by awaduharatk** [comment]
トランザクション制御を行う関数を実装しました。
トランザクションをネストさせる動作は少し考えなければいけなさそうです。
https://github.com/temp-go-dev/sample-api-gin/commit/859bc6e9aeb2a95bcf1cae6ad5209c1e3e9f9039

Master/Replicaはdb.goのinitで2つ初期化してgetできるようにしておけば実現可能です。

**Comment by awaduharatk** [comment]
> トランザクション制御を行う関数を実装しました。
> トランザクションをネストさせる動作は少し考えなければいけなさそうです。
> [temp-go-dev/sample-api-gin@859bc6e](https://github.com/temp-go-dev/sample-api-gin/commit/859bc6e9aeb2a95bcf1cae6ad5209c1e3e9f9039)

試してみましたがうまくいきませんでした。
調べたらGORM自体が対応していないようで、実現するには生のSQLを使ってやってくれとのことらしいです。[Nested transactions #699](https://github.com/jinzhu/gorm/issues/699)

**Comment by takashno** [comment]
【メモ】
実際の生のSQLでやるというのが、
BeginとかをSQLの中で自分で組むという話でした。
ということは、CommitとRollbackも同様？
