### ISSUE TITLE
環境変数の取り扱い方

### ISSUE THREAD

**Issue by takashno** [temp-go-dev/consider#25]
# 環境変数の取り扱い方

## 目的・概要・ゴール
- 目的
環境変数の取り扱い方を調査・検討

- 概要 
  - 環境変数の取り扱い方を調べる
  - 取り込み方を調べる
  - 環境デプロイを考慮した与え方を調べる

- ゴール
  - 議論＆決定

**Comment by takashno** [comment]
ビルド時にtagsを指定することができる。
そのtagsの値が指定されているときだけビルド成果物に含める？よういできると思われる。
そうすることで、環境毎に実行するソースコードが分けれるということみたい。

[build tagsを使ったビルドの切り分け](https://qiita.com/ueokande/items/fac0d1219dbbc8f44db7#build-tags%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%9F%E3%83%93%E3%83%AB%E3%83%89%E3%81%AE%E5%88%87%E3%82%8A%E5%88%86%E3%81%91)

実際にenvの取り扱いと混ぜてどうするのが良いか探る必要がある。

**Comment by takashno** [comment]
https://github.com/temp-go-dev/consider/blob/feature/25_environment/decisions/0004-environment.md
環境変数の取り込み方として、`GoDotEnv` とか書いてしまいましたが、
ちょっと微妙な気がしてきました。
Docker等のコンテナ技術を使ってデプロイする場合に、ファイル読み込みだと都合が悪い気がします。
イメージの中に環境依存ファイルを置く等は避けるのが定石だと思いますので。

やはり、環境変数から直接モデル等へバインドするだけにとどめておいたほうがよさそうですね。
環境変数はコンテナ起動時に与えるイメージです。（ファイルもしくはスクリプト）

`SpringConfigServer` みたいな考え方で起動時に読み込めたら嬉しいのか？とかも考えましたが、
あんまり現在の自分では旨味を見出せず…
変数リフレッシュの必要有無と頻度にもよるのでしょうが。

**Comment by awaduharatk** [comment]
結果を記載しました。
ご確認お願い致します。
https://github.com/temp-go-dev/consider/blob/feature/25_environment/decisions/0004-environment.md

**Comment by takashno** [comment]
確認しました。
ありがとうございます。
マージ＆クローズします。
